Ваша задача придумывать новые названия для товаров IKEA. Что бы не сойти с ума вы хотите автомадизировать задачу. У вас есть большой список существующих названий IKEA, напишите нейросеть генерирующие новые наименования.

![An image](https://zagge.ru/wp-content/uploads/2020/02/13333008.jpg)


In [ ]:
from __future__ import print_function
import os
import random
import numpy as np
import torch
import torch.nn as nn

print(torch.__version__)

1.9.0+cu102


In [ ]:
names = ['ХЕММАБАК', 'РЕНБЛОММА', 'ЗАКАРИАС', 'ЛЕДФИР', 'ТОРКАД', 'ДИСКАД', 'СОЛЬФРИД', 'ВЕКЕТОГ', 'ЛУНДСЛОК', 'ГАРНЕРА', 'АРНАГЕР', 'ФРЕДДЕ', 'ХЕЛИКС', 'ЛИНДКНУД', 'ФОРМИДАБЕЛЬ', 'БИЛЛАН', 'ГРУНДАД', 'УТЛЭГГА', 'ГУНСТИГ', 'ДЖУБЛ', 'ЛЭТТЛОССАД', 'СПЭККА', 'КОРКЕН', 'ЛАДДА', 'СМАКСАК', 'ЭНРУМ', 'ФИНМАЛЬД', 'САНДВИВА', 'ВИДЕБЭК', 'ИСБЕРГЕТ', 'НИТТИГ', 'СВЭВАНДЕ', 'ЛИКСГУЛЬТ', 'ЛЕРХАМН', 'СПОРАДИСК', 'ФРЕСЕТ', 'ХИЛЛИС', 'ТЭРЕНДО', 'ФЬЕЛЛЬБРЭККА', 'ВИССВАСС', 'БУЛЛИГ', 'ФИЛЬТ', 'СТЭРНСТАРР', 'АЛТАППЕН', 'ТИССЕДАЛЬ', 'ЦИРКУСТЭЛЬТ', 'ГУЛЬТАРП', 'ТЕМПЕРЕРАД', 'РАЙТАН', 'СКОГСТА', 'СВАЙПА', 'ЭЛЬДТОРН', 'КРЮДДСАЛЬВИА', 'ФИЛУР', 'ЛИНДВЕД', 'СТУРАВАН', 'ЮНИМАГНОЛИЯ', 'СТРАНДФРЭНЕ', 'БЕНГТХОКАН', 'АЛПДРАБА', 'НАТТЭСМИН', 'ТАЛЬДЖЕ', 'ОФТАСТ', 'ФЕНОМЕН', 'ИРМАЛИ', 'ПЛУМСА', 'ЛЕГИТИМ', 'ХЭНГИГ', 'ПОЛАРВИДЕ', 'ГЭМЛЕБИ', 'СТАЙЛИГ', 'ХИЛЛЕСТАД', 'ВАТТЕНКРАССЕ', 'БЕСТО', 'РОТСУНД', 'ЛЕРБУДА', 'СТИГ', 'КРУСНИНГ', 'СМОРИСКА', 'ХЕММА', 'ГЛЮПЕН', 'СНАББАКАТ', 'КАУСТБИ', 'АНСЛУТА', 
         'ФЛОТТИГ', 'УППЛАГА', 'ВИКХАММЕР', 'ВИТМУССА', 'ХАМАДАН', 'ЛОВРУП', 'АНФАЛЛАРЕ', 'РИЭТ', 'СТЕНСЕЛЕ', 'ЧИЛИПУЛВЕР', 'ХАВСЕН', 'СТРАНДМОЛКЕ', 'ПИЛЛЕМАРК', 'РИЛЬ', 'ХОРНЕН', 'ЙОМНА', 'МОПСИГ', 'ХЕЛЬМЕР', 'ГУЛСПАРВ', 'КНИПСА', 'БЕХЭЛПЛИГ', 'БЭЮБЛАД', 'АДРИНЕ', 'БРАВУР', 'КАРЛБИ', 'ФЭРГРИК', 'ТРЭДКРАССУЛА', 'СТУРХАГА', 'МУСКОТБЛОММА', 'ГЛИТРИГ', 'ФЬЕЛЛЬБО', 'ХОВОГ', 'САННАХЕД', 'САЛТИГ', 'КНАСТРИГТ', 'РОСКУГ', 'СВАЛЛЕТ', 'ОКСБЕРГ', 'ДРАЦЕНА', 'ОРСТИД', 'ТОМЕЛИЛЛА', 'МАРРЕН', 'РИКЕНЕ', 'ТИСНЕС', 'ЛИВНЭРА', 'ГРИМХУЛЬТ', 'СТРИММИГ', 'НИПОН', 'АЛОЭ', 'ШЭРМЛИЛЬЯ', 'ТИЛЛБРИНГАРЕ', 'ФЬЕЛЛА', 'ФИНИК', 'ТОЛКЕН', 'КРУММЕЛУР', 'РЕСО', 'НЮККЕЛЬН', 'ЛИККАД', 'ХУСВИКА', 'НЭРСЕН', 'СКЮНКЕ', 'ГРИМО', 'ЛЮНДЕРУП', 'ЭКНЕ', 'ПРОППМЭТТ', 'ЛАКК', 'МОРЛИДЕН', 'ВЭЛЬДОФТ', 'МАККАПЭР', 'ТИЛЛЭМПАД', 'БАККСМУЛТРОН', 'ОППЕН', 'СИМРИСХАМН', 'БРИЛЬЕРА', 'ШЭНКА', 'КНОППЭНГ', 'РОЛЛЬСБУ', 'БЕСТОДД', 'КНИКСХУЛЬТ', 'БЕРГЕНЕС', 'СКИВХОЛЬМЕ', 'СИГФИН', 'ТЭЛЛМО', 'НОЙИГ', 'БАЙК', 'ДОЛЬД', 'ЛАНТИВ', 'РАМСБОРГ', 'ХЕМНЭС', 'БЕНГТА', 'БРОВИКЕН', 'ПЛАТС', 'МОЙНА', 'БЬЯРНИ', 'РОТГУЛЬТ', 'ГУЛЬТЕТ', 'ДЭНКА', 'ДОКУМЕНТ', 'ЛОДРЭТ', 'МЕЛЬТОРП', 'ЛЕЙРВИК', 'БЕНЛОЙА', 'КОНСИС', 'ДЮЛИГ', 'ЛОМВИКЕН', 'ХОРТЕ', 'ПЕЛЛЕПЛУТТ', 'НЬЮТНИНГ', 'ГРЕЙГ', 'КЛЭММЕМАККА', 'ХИЛЬЯ', 'СТЬЕРНЛОК', 
         'ИНТРЕСАНТ', 'ЛУДДРОС', 'БЛАНК', 'МАТЭЛСКАРЕ', 'ГАЛИАМЕЛОН', 'ЛЕРСТА', 'МЕХАМН', 'НИФОРС', 'ФУЛЛТАЛИГ', 'СОНГЕСАНД', 'ГОДДАГ', 'ХОВЕРА', 'СТЭЛЛ', 'ФНУРРА', 'ХОПОТ', 'ПЕЛАРГОНИЯ', 'ДРАГГАН', 'МАЛИНДА', 'ПЛОМБО', 'ПРЕССА', 'ЛЬЮВАРЕ', 'ЮККЕ', 'АВСКИЛЬД', 'РИНГСТА', 'СКОГСФРЭКЕН', 'ФИННСТАРР', 'ОЛАНДСРОТ', 'ТОРГЕРД', 'ДРАГОН', 'РАГГДРАБА', 'КРАНСБОРРЕ', 'КРОНЭРТ', 'БОТКИРКА', 'РУММЕТ', 'ЭНЭБИ', 'ТЕРЦИАЛ', 'СТОРХЕТ', 'БУСА', 'СКВАЛЛЬРА', 'СКРУТТ', 'МАРТИН', 'АЛЬСЕДА', 'ЛАНГСТЕД', 'СОЛЬСКУР', 'БРИМНЭС', 'ФРЮСА', 'ЮПВИК', 'СМАКГЛАД', 'ТОРСБИ', 'ВИКФЬЕРД', 'МИКСТУР', 'ПЛАСТИС', 'ФЛИТИГХЕТ', 'СКОГССТАРР', 'КОМПЛИМЕНТ', 'ФОРФИНА', 'ВОГЛИГ', 'НИБОДА', 'МАРГИНАТА', 'СИНДАЛЬ', 'КЛАППА', 'ХОГКЛАССИГ', 'ЛИЛЛЬРЕВЕТ', 'ФИННТОРП', 'БЕСЕГРА', 'УРБАН', 'КВИКСУНД', 'БАКГЛАД', 'СТЭРНАНИС', 'ФЬЕЛЛАРНИКА', 'МАТЛЮСТ', 'ЛИВЛИГ', 'УГГЛЕМОТТ', 'ГРУППЕРА', 'ВОРТРИ', 'ВАДХОЛЬМА', 'КРАББ', 'ФОРСАНД', 'КРУСТАД', 'ЛИЛЛЕПЛУТТ', 'БОЛЬМЕН', 'ЧОСИГТ', 'РЕНОДЛАД', 'БЛЭДДРАРЕ', 'КЛИПСК', 'НЕРЕБЮ', 'ШИН', 'ГУЛЬВЕД', 'БЕРТИЛЬ', 'КОЛЛУНД', 'ЦИЛЛА', 'ИДАНЭС', 'ВИЛЬТО', 'БРУСЕН', 'СТОРСИНТ', 'МЕТТАЛИСЕ', 'ЭЛЬВСТАРР', 'ТРОММА', 'САГАЛОВИЗА', 'КОППАРБЛАД', 'СКОГСО', 'АННАКАЙСА', 'ТЮККЕЛЬН', 'ЭТБАРТ', 'СКОНКОР', 'КИЛИМ', 'СКЭРИГ', 'ТВЭЛЛЕН', 'СОККЕРЭРТ', 'КИЛИГ', 'НОРРАРИД', 
         'КРУСОН', 'ГАЛЛБУДА', 'ОРТФИЛЛЬД', 'ОРДЕНСФЛИ', 'ЭЛЬФРИДА', 'РАКЛЕВ', 'БОЙА', 'ВИТАБИ', 'РОХУЛЬТ', 'РОЗЕНХЭТТА', 'БАККИГ', 'ШОТТИС', 'АНАНАС', 'ВИМУНД', 'СНИДАД', 'ЛАППТОТЕЛЬ', 'ГИМАЛАЙАМИКС', 'ЦИЛИНДР', 'ВИВИАННА', 'ХАНДСКАЛАД', 'МАНИКК', 'ВОЛЬФГАНГ', 'ЛАГКАПТЕН', 'ТИНАД', 'РОВАРОР', 'РЭННИЛЕН', 'МУССЕЛЬБЛОММА', 'ТОНСЭТТА', 'СОККЕР', 'ВЭРМД', 'УНДЕРВЕРК', 'ЛИДГУЛЬТ', 'БИНТЬЕ', 'ЛЭТТ', 'ВИСПАД', 'ТОСТХУЛЬТ', 'БЭККСЕДА', 'МУЛА', 'КЮРА', 'МЭРИТ', 'ГОРЛИГ', 'ХЮВЕНС', 'БЕРЭКНА', 'ПИННАРП', 'ГОДАФТОН', 'ОБИОН', 'ХОККСУНД', 'МИЛЛБЕРГЕТ', 'ОУМБЕРЛИГ', 'СТИККАТ', 'ГОДТАГБАР', 'ТЕРЬЕ', 'ИНГРУН', 'СНИТТА', 'АНТОНИУС', 'ХАВСКАРП', 'ФРАКТА', 'ЭЛВАРЛИ', 'ТОГА', 'КВАРНВИК', 'МЕРЕТЕ', 'СЛИПСТЕН', 'БУРС', 'НЭТВЭРК', 'НУТ', 'БАГИС', 'ЭФТРЕСТРЭВА', 'ВИЛБОРГ', 'САМТИККА', 'ЭЛЬПСАМ', 'ТРОЙКА', 'ЛИАТОРП', 'СИРЛИГ', 'БОТАРЕН', 'АУЛИ', 'КОПЛА', 'ПЛУРИГ', 'ЛИКТФИББЛА', 'ТОРКЕЛЬ', 'САНДЛУПИН', 'АГЕН', 'ВЕССЛА', 'САНДИГ', 'ВИТВАЛ', 'ЭЙЛИФ', 'ГАББЕХ', 
         'БЛОХУВА', 'ЭКСОПП', 'НОРДКИЗА', 'ХЕКТОГРАМ', 'РЕИНСВОЛЛ', 'КВОТ', 'САТСУМАС', 'МАРИУС', 'БЕКВЭМ', 'ЛИВСЛОНГ', 'ЛЮДЕРСХОЛЬМ', 'ФЬЕЛЛЬМОТТ', 'СЛАТТУМ', 'ЮЛЛЕВАД', 'НОРДРЭНА', 'БЮГГЛЕК', 'СТОЭНСЕ', 'ДАРРОКА', 'БЕКАНТ', 'СЛИББ', 'ГЛЕС', 'АНИЛИНАРЕ', 'КАРАФФ', 'ЛИХОЛЕН', 'НОРНЭС', 'ИГАБРИТТА', 'ГУЛЬМАЙ', 'ЛЕНАКАРИН', 'БИССИНГ', 'ФЭЛЬТМАЛ', 'ХАСВИК', 'СКРУВСТА', 'ФИКСНЭС', 'ВАСЕН', 'ЛИДКУЛЛЕН', 'СЮВДЕ', 'ГНАРП', 'МАНДАРИНРОЗ', 'СТОП', 'ТИНГЕН', 'СУММЕРА', 'БУХОЛЬМЕН', 'РАДГРЭС', 'ДАНДЭРЮД', 'ЭФТЕРФРОГАД', 'МОЛЬТЕ', 'ФЛИНТАН', 'СКАРСТА', 'ОДДХИЛЬД', 'ХЕДЕРА', 'СОНГЛЭРКА', 'ГРУСНАРВ', 'РОЗЕНХАЛЛОН', 'ДУГГРЕГН', 'НОДЕБО', 'СТРАНДМОН', 'ГРИЛЛА', 'ПЛАТСА', 'УППЛЕВА', 'ЛЭРБРО', 'КАРМСУНД', 'РОЗЕНСКЭРМ', 'ЙЭТТЕЛИК', 'КВЭЛЛЬСВАРД', 'НАТТСМИГ', 'СТУРСЕЛЕ', 'НИННИ', 'ИНБЬЮДЕН', 'СЭЛЬЯН', 'СТЭЛЛА', 'СТРОЛА', 'БИТТЕРГУРКА', 'ТРУГЕН', 'АЛЬМТЬЕРН', 'СТУВА', 'ТАЛАНДЕ', 'БЕХАГФУЛЛ', 'ХЭТЛЕВИК', 'ГИГАНТИСК', 'МОЛА', 'УППВАН', 'СВЕНСОС', 'ЛАГТ', 'ГАММАН', 'ВИЛЬДКОРН', 'ГЕРДИС', 'ЛУСТИГТ', 'ЛУНАРП', 'БЕТИДЛИГ', 'ТОССИГ', 'ТРЭТТЕН', 'ХУТТЕН', 'ХОДДА', 'ХИЛЛАРЕД', 'МАРИАТЕРЕС', 'ХАЛЛВИ', 'ПОРТИС', 'ГЕССАН', 'ТРЕТТИОТРЕ', 'СЕЛЬСВИКЕН', 'НОРДЛИ', 'ТРУФАСТ', 'СТАБИЛЬ', 'СКОРВА', 'НОРДБИ', 'РОТФИБЛА', 'ДИРЕКТ', 
         'ФОРСО', 'АЛЬСТЕРН', 'КЛОККАРЕН', 'РИКЛИГ', 'ФИСКОН', 'ЛОТЕ', 'МУРВЕЛЬ', 'ХЕММАХОС', 'ХЭЛПРЕДА', 'ГОЛДЕН', 'ТРОД', 'ПОЭНГ', 'ПЛЕЙА', 'СМОСПОРРЕ', 'СЛУТЕН', 'КРИЛЛЕ', 'СТЕНЛИЛЛЕ', 'ТИЛЛСПЕТСАД', 'ТОРКИС', 'КАСТРУЛЛ', 'ТОССБЕРГ', 'ГЛИС', 'НОРДВИКЕН', 'ДЮФТ', 'ФЛЮТТБАР', 'ЭКЕДАЛЕН', 'СТАРТТИД', 'ВУКУ', 'РИАН', 'РАНСБИ', 'ВИППЭРТ', 'СТОККАРИД', 'КЮРРИБЛАД', 'НУМЕРЭР', 'БИЛЛИ', 'ДЬЮР', 'ТРОВЭРДИГ', 'БУМЕРАНГ', 'ЛИННМОН', 'СУАРЕ', 'ЭПЛАРО', 'ИНГОЛЬФ', 'ЭНГСКОРН', 'СОММАРМАЛЬВА', 'ГРАДВИС', 'СПАТИФИЛЛУМ', 'ВЕРА', 'МУЛИГ', 'ТИДВАТТЕН', 'ХАВСТА', 'БУСБАССЕ', 'МАТМЭССИГ', 'ПОРТЕНШЛАГА', 'РЕДА', 'ФАВОРИСЕРА', 'ЛИЗЕКИЛЬ', 'СТОДЬЯ', 'ЛИЛЛЕГЕРД', 'СУННЕА', 'ВАНИЛЬСТОНГ', 'ВАТТВИКЕН', 'ДЬЮПФРЮСА', 'РОЗЕНМОТТ', 'СНИГГИНГ', 'КОРНАН', 'ВОКСНАН', 'ПУДДА', 'ГОСИГ', 'КНОКСХУЛЬТ', 'СТРОФЛИ', 'АЛЛЕХАНДА', 'СТОРЭТАРЕ', 'ГРИТЭ', 'ЭКОРРЭ', 'Н', 'БЛАНДА', 'БРУР', 'ФРЕДВАНГ', 'ДЬЮНГЕЛЬСКОГ', 'РЮТМИСК', 'УППГРАДЕРА', 'ФЛЮНС', 'СЬЕЛСЛИГТ', 'ФЭРГКЛАР', 'БЕМОТА', 'ГРАСИОС', 'ОСТКЭКА', 'ИННЕРЛИГ', 'ХЭДРА', 'НЕДИСАД', 'МИККЕ', 'ВЕРКЛИГХЕТ', 'ЭДСВИК', 'СКУГГБРЭККА', 'СЭВСТА', 'САНЕЛА', 'ГАРНИТЮРЕН', 'МАРЮД', 'ЛУРВИГ', 'ГЛИТТРАН', 'ДУКТИГ', 'ЛОКАЛЬТ', 'СЕТСКОГ', 'УНДВИКА', 'СОНГЕ', 'ПЬЕТТЕРИД', 'ПИННИГ', 
         'ТОРРИЛД', 'АПТИТЛИГ', 'ПЛУФСИГ', 'КНОТТЕН', 'ГУЛЛИВЕР', 'КАФФЕСУГЕН', 'МОАКАЙСА', 'КАТТЕВИК', 'СМОСТАД', 'ПЕРСИЛЛАДЕ', 'ФЛАКНАН', 'БЭСТИС', 'ДИНЕРА', 'ДИМПА', 'ЙЭРПОН', 'УТРУСТА', 'ИНДИРА', 'ВЭДРА', 'БЕРГХАЛЛА', 'ФЕГЕН', 'БАЛАНСЕРАД', 'ТИЛЛЕВИПС', 'КИННЕН', 'ПАТРУЛЬ', 'БЕРГСХУЛЬТ', 'МЕЛОДИ', 'ДАГОТТО', 'УНДЕРЛАГ', 'АННОНС', 'ЙЭТТЕСТОР', 'РУНДАРЕ', 'ВИСБЭКК', 'АКСВЕРОНИКА', 'ИХОЛЛИГ', 'ЭНУДДЭН', 'БЛОБЭРСМОТТ', 'ВЕННЕСЛА', 'ОМТЭНКСАМ', 'ЛАНДСКРУНА', 'ЭСКЕЛЕН', 'ТИБЛ', 'ТОФТБЮН', 'ЭНГСМОТТ', 'ГРОНБИ', 'БЕРГВЕН', 'ЛЮКТЭСМИН', 'ТУРИЛЛ', 'ФАМНИГ', 'ВАЛЬФРЕД', 'СВЕНСХУЛЬТ', 'ЛОППСТАРР', 'ВИСТХУС', 'КУЛИНАРИСК', 'ГУНДЕ', 'НИДАЛА', 'СПОРТСЛИГ', 'ГУЛЛИГЭСТ', 'ЭРИНРА', 'ВИДГА', 'КРОППСВАРМ', 'БЕКРЭФТА', 'РУТИГ', 'СПЕТС', 'ВАЛЛЕНСВЕД', 'РИССЛА', 'ФОЛЬСАМ', 'ЦИССЭН', 'УЛЬРИКСБЕРГ', 'ТРЕБЛАД', 'РИСАТОРП', 'БРУНКРИСЛА', 'ОДВАЛЬД', 'ЛОТСАС', 'ОВЕРМЭТТ', 'ФРИДАНС', 'БЕГОВНИНГ', 'ХОЛЬМСУНД', 'ЮЛВАЛИ', 'ДАЛЬШЕР', 'ФРАМФЮСИГ', 'МАЛЬМБЭКК', 'ТИГЕ', 'ХУВУДРОЛЛ', 'КЛАБ', 'НОЛЬМИРА', 'СТЕМЭТАРЕ', 'МОЛАРБОРСТЕ', 'СОРТСО', 'ВИНТЕР', 'ЧАЛЛА', 'КРЕСТОВНИК', 'КЕЙСЕРЛИГ', 'ОДДРУН', 'ХИМЛЕОН', 'ЛИНДЭЙА', 'САЛЬТХОЛЬМЕН', 'МОРГЕДАЛЬ', 'ФЛУГБУ', 'ПОКАЛ', 'ГЕРХИЛЬД', 'БЕЛУДЖ', 'ДРАГАН', 'БЕДИНГЕ', 'РАДАРБУЛЛЕ', 'ГУДИС', 'УРСКОГ', 'ЭКЕТ', 'ФЛЕККЕ', 'ЛАКСНЕ', 'ФИРЕСДАЛЬ', 'ПИНГЛА', 'ЛИЛЛА', 'ЭНГАРНА', 'ЭКБИ', 'РОККОН', 'ГЛАСИГ', 'ВИХОЛЬМЕН', 'НИССЕДАЛЬ', 'ХИММЕЛСБЮ', 'ОСТБИТ', 'БОНДХОЛЬМЕН', 'ДИНИНГ', 'КОРСМОН', 'ФИЛОДЕНДРОН', 'ХЕЙНЕ', 'МАТТРАМ', 'ЭППЕЛЬВИКЕН', 'КЛИНГСБУ', 'ФЕЙО', 'ПС', 'СВЭРТА', 'ТАГГВАЛЛЬМО', 'СВАЛЛЕРУП', 'ВОРБРЭККА', 'ЛИСАБО', 'ПРУТА', 'РОРСЛЕВ', 'ИДОСЕН', 'ЭКБАККЕН', 'ШЕФФЛЕРА', 'ДЖЕРСИ', 'ЛИЛЛЕВОРДЕ', 'ФОНГСТ', 'МОЛСЕЛЬВА', 'ЭКСЕПТИОНЕЛЛЬ', 'СТЭМ', 'ФРОСТИГ', 'СЭФФЕРОТ', 'РИГГАД', 'ЛОСТАГБАР', 'ТРЮББНАТЕ', 'ФЮББЛА', 'МАРЬЮН', 'БОРЬЯ', 'ЛУНДШЭР', 'АДАНСОНА', 'ВРЕНСТЕД', 'ЭКОЛЬН', 'ЭГГЕЛЬСТАД', 'МИДАЛ', 'МАТТРАДИТИОН', 'ХОЛЛБАР', 'ФОРСЛАГ', 'ВОКАЛИССА', 'ФОРСЕГЛА', 'КРЮДДПЕППАР', 'ЛИЛЛЬХУЛЬТ', 'БЕХЭНДИГ', 'НОРДМИРА', 'ПУДЕРВИВА', 'МАЛФОРС', 'ЛЕННАРТ', 'СНЭПП', 'МОСХУЛЬТ', 'БРАНЭС', 'КРАМИГ', 'НЮХОЛИД', 
         'ТРАНГЕТ', 'РУНДСТАРР', 'ФНИСС', 'ФРИЕЛЕ', 'БЛОТСНО', 'РЕГНСКУР', 'ЛУННОМ', 'ИДАСАРА', 'ГРУНКА', 'ХИЛЛЕБОРГ', 'АЛЬСТРАД', 'БЛЕККА', 'ФУЛЛСМОКАД', 'ХОППВАЛС', 'ИРМЕЛИН', 'ЛАНЕБЕРГ', 'ПЛУГГХЭСТ', 'АСКАРИА', 'СКАКИГ', 'ХАМЕДОРЕЯ', 'ЭКСТРАКНЭКК', 'ЛОТС', 'ГУББАРП', 'ХАМНШЕР', 'БЛОМСТЕРБОНА', 'ТОРВФЛЮ', 'КОППАРРАНКА', 'КИЛАОН', 'ЛИКСЕЛЕ', 'АНРЭТТА', 'ЭНТИДИГ', 'КАФФЕБОНА', 'ТЮВЕЛЬСЕ', 'САГСТУА', 'СТУК', 'ЛЕРБЕРГ', 'ОКСБИ', 'ВОРЕЛЬД', 'ТРИСИЛ', 'ХАННЕЛИЗЕ', 'СНАРЛИГ', 'ФРАМТРЭДА', 'ХЭЛЛАН', 'КЭППХЭСТ', 'ТИПХЕДЕ', 'ХАРРИ', 'ХЕДЕРЛИГ', 'ФИКУС', 'НИМО', 'ЛИСМАРКА', 'АЛЕКС', 'ХЕЛЬГУН', 'МОППА', 'КНАППЕР', 'РИНДСХОЛЬМ', 'КАЛЛАКС', 'ДАЛЬФРЕД', 'ГАЛЕЙ', 'СПРИТТА', 'СОККЕРТАКА', 'БОРГХАМН', 'МАЛВИК', 'ХАФСЛО', 'СТУРСК', 'МАЙРИД', 'УЛЛЬВИДЕ', 'ЛЭТТБАКАД', 'ТЕОДОРЕС', 'ФЬЕЛЛЬХАВРЕ', 'ГЛАТТИС', 'СПРАЯ', 'БИРТНА', 'ФЛОДАРЕН', 'ФИСКБУ', 'ТЕНГУЛЬТ', 'ГРИЛЛЬСКЭР', 'ТИЛЛСЮН', 'БЭГАРЕН', 'ЛОНГДАНС', 'СОЛЬХЕМ', 'СЕВЭРД', 'АЛЬФТА', 'КРОНИЛЛ', 'БРЮНСТА', 'ЧУСИГ', 'ФРУКТСКЭЛ', 'КЛИББГЛИМ', 'БЭНГБУЛА', 'МАТРАНД', 'РЕВЛУММЕР', 'ЛИЛЛОНГЕН', 'ТРАМПА', 'ДЮТОГ', 'НИССЕ', 'КЕМИСК', 'РОКЭЛЛ', 'КАВАЛЬКАД', 'БОАКСЕЛЬ', 'МИЛЬСБУ', 'ТЮДДАЛЬ', 'ВЭКСБУ', 'ИННЕР', 'БЛЕКБЕРГЕТ', 'ФОРМЕДЛА', 'ЭСТАНО', 'УТБЮТТ', 'СВАЛЬНЭС', 'СОРБЮН', 'БЛОХЭЙ', 'ТОЛЬФТ', 'БРУСАЛИ', 'КЛИППАН', 'САЛЬЕН', 'ФРИХУЛЬТ', 'ХЭНГА', 'ХОРНИНДАЛЬ', 'ИНГВАР', 'ТОСТЕРО', 'КНОППАРП', 'ХОВСТА', 'ТЕККЕХ', 'МИННЕН', 'САМЛА', 'ЛАМПАН', 'СЛИРА', 'ГРОСИДАН', 'ФИКСА', 'ЛИЛЛОСЕН', 'ЭКРАР', 'ХАКВИНГЕ', 'ОПЛЕВ', 'ГЛАДЕЛИГ', 'РОДФРОГА', 'ПАННО', 'ТИЛЛСТЭЛЛНИНГ', 'БОНТОФТА', 'ГЕСТАЛЬТА', 'САЛЬВИКЕН', 'СКЭРХАМН', 'БИЛЬСБРУ', 'ЦИТРУСКРЮДДА', 'ЛУРТ', 'МОНСТЕРА', 'СЭЛЛЬСКАПЛИГ', 'ПОЛЬ', 'НЕГЛИНГЕ', 'РАНАРП', 'ЭНСЕН', 'ВАНДРИНГ', 'ГРУНДВАТТНЕТ', 'МАТИЛЬДА', 'ЛИСТЕРБИ', 'ХАМПЭН', 'ФРЕДЭН', 'ЙОФРИД', 'КНАРРЕВИК', 'ВАДХЕЙМ', 'ЛИЛЛЬНАГЕН', 
         'ЭЛЕГАНС', 'ОПХУС', 'ИРЬЯ', 'ТУРД', 'ВЭГГИС', 'ИДЕАЛИСК', 'СКОДИС', 'ГРАНБОДА', 'ИКОРННЕС', 'ХАРЕИД', 'ИДЕНТИТЕТ', 'АГАМ', 'ХЕМБЮГТ', 'ОФАНТЛИГТ', 'РИНГБЛУММА', 'ТРЕТУР', 'ЭКТИГ', 'ЛУСТИГКЮРРЕ', 'СТАВРЕБЮ', 'ВАДСО', 'ЛАГАН', 'СТЭЛЛЬБАР', 'КЭЛЛЬНА', 'ГОДИХУС', 'СЛЭКТ', 'ВИГДИС', 'ЛЭТСАМ', 'МОРБИЛОНГА', 'РУНШЕР', 'ГНЕДБИ', 'БОРСТАД', 'БОРГЕБИ', 'БРЭДА', 'КЛЕЙС', 'УПХЕТТА', 'БОККАРА', 'ГАЛИОН', 'ФАНБЮН', 'РОГРУНД', 'ГРУННАРП', 'СТРОМЛИНЬЕ', 'ЛИВСЛОГА', 'СПАРЛОГА', 'КИЛСВИКЕН', 'ТВЭТТАД', 'СТАДСДЕЛЬ', 'АВСИКТЛИГ', 'ГУЛКАВЛЕ', 'СТРЮКИС', 'РОТФЬЕРИЛ', 'ВАЛЛАМОССЕ', 'ПЛАТБОЙ', 'ЭРФОРДРА', 'СМЭККЕР', 'ПИВРИНГ', 'СУННЕРСТА', 'ВЭННЕОН', 'ГАЛАНТ', 'БЕРГПАЛМ', 'ХОККОСЕН', 'СНУББИГ', 'ХАВОРТИЯ', 'ПЮНТЕН', 'РЕГОЛИТ', 'ФЛОДИС', 'ФЮССЕ', 'УППВАКТА', 'РАККЕСТАД', 'ТРЕНСУМ', 'СКАЙРОН', 'МЭЛЛЬСТЕН', 'ХАККИГ', 'ХАККОС', 'ЛОНГФЬЕЛЛЬ', 'ПРИККИГ', 'ФЛЕРТИДИГ', 'ТОМАТ', 'ИВАР', 'СКЕЛУНД', 'ХУСЕТ', 'ЭЛЛЬ', 'ЛОНГУДДЕН', 'ГРИЛЛЬТИДЕР', 'УТРУСТНИНГ', 'ЛЕКСВИК', 'СКЭГГОРТ', 'ГРОВАЛЬ', 'НОРДЕН', 'ТАККАН', 'ОМСИНТ', 'УББЮН', 'ТОРАРЕД', 'МАКСИМЕРА', 'ПЕРСИСК', 
         'МУСКОТ', 'СВЕНШЕР', 'РИКТИГ', 'ГРИНСОПП', 'ХИЛЬДЕГУН', 'ДИСТРИКТ', 'СВАЛЬК', 'УТОКЕР', 'МЭСТЕРБИ', 'ХОРНАВАН', 'ИНГУ', 'ХЕДДАМАРИА', 'ФОЛКЬЯ', 'ХАРРИЕТ', 'ТАККСАМХЕТ', 'ТОБИАС', 'МЭТВРО', 'ОРРНЭС', 'СКОГСВИКЕН', 'МАЛЬСКЭР', 'ДЮГРИП', 'ВАНЛИГЕН', 'ЙОКМОКК', 'ЛИВСГНИСТА', 'ХЭГСМА', 'ФРАНКЛИН', 'БЭНККАМРАТ', 'КОПЕНГАГЕН', 'БЬЮРСТА', 'ХЭЛЛЬВИ', 'БИССА', 'МЕДЕЛЬСТОР', 'СИЛВЕРХОЙДЕН', 'ПЕЛАРБОЙ', 'УТНЭМНД', 'ХЕНРИКСДАЛЬ', 'СИННЕСРО', 'УППТОГ', 'УГИЛЬТ', 'СКЭРАНДЕ', 'БОСНЭС', 'АДИЛЬС', 'АКРОБАТИСК', 'БЕРГИГ', 'САНДЛАНДЕТ', 'ДУВХОЛЬМЕН', 'ТУКИГ', 'ФУЛЛСПЭККАД', 'ХОЛЬМЭ', 'МОЛЕРОС', 'ЭРТОФТА', 'ИГЭРДИГ', 'РАМСО', 'ЯНШО', 'СВАРТО', 'ЮСТИНА', 'КЛОККИС', 'СТЕФАН', 'РОТТА', 'ЛЭТТХЕТ', 'ХЭЛПА', 'БОРДИГ', 'ХОЛЬМСЕЛЬ', 'КАТРУП', 'НЕЙДЕН', 'ФОРТЙЮСНИНГ', 'РАМСГУЛЬТ', 'КОЛОКОЛЬЧИК', 'ИВРИГ', 'РАГГИСАР', 'КИННАРЕД', 'ПРАКТВЭДД', 'МЮСКГРЭС', 'ГЕМАК', 'ТРОЛЛМАЛ', 'ЭППЕЛЬРОС', 'ПОДРАГ', 'ФЕСТЛИГЕТ', 'ХАННАЛИЛЛ', 'ВИТЛОК', 'ОСТЕРНЭС', 'САМАРИТ', 'АНТИЛОП', 'ХУТТРА', 'ГОДМОРГОН', 'ЭББАТИЛЬДА', 'РАМСЕЛЕ', 'РЭККА', 'МАММУТ', 'ФИНАНСИЭЛЛ', 'КЛУББСПОРРЕ', 'СОЛГУЛЬ', 'БЛОМНИНГ', 'ХАВЕРН', 'ЭЛДБЕРГЕТ', 'СПИКВАЛЛЬМО', 'ХИНДОС', 'САЛОН', 'СОЛЛЕРОН', 'ФРИДЕНЭ', 'БРОГРУНД', 'КНАГГЛИГ', 'ФЬЕЛЛБЕРГЕТ', 'ТИЛЛГИВЕН', 
         'СТАВН', 'ТРОЛЛЬПИЛ', 'ЛИНДБЮН', 'ЛЬЮСАНДЕ', 'КВИТТЕРА', 'ГЕРЛЕВ', 'БЬЕРСЕН', 'КОМПАКТА', 'ФИНФОРДЕЛА', 'КРОКИГ', 'ВЭРЛДЕНС', 'КРИСТРУП', 'ВЕДБУ', 'ЛОККБЕТЕ', 'СОЛАРВЕТ', 'ТИНГБИ', 'ГРУНДТАЛЬ', 'МИТТБАКК', 'СКОНЕВИК', 'ДИГНИТЕТ', 'ВИДЬЯ', 'СМИККА', 'СКУББ', 'КЛАСЕН', 'УРСГУЛЬТ', 'ТОТЭБО', 'ТЭРНАБИ', 'ВИТАМИНЕР', 'ТРОЛЛЬДРУВА', 'БЛЭДЬЕН', 'НЭРСНЕС', 'СМЭГЛИ', 'ХЕМЛАГАД', 'СКУРУП', 'ФЛЮНДРА', 'СТИНАМАЙ', 'БЭРБАР', 'ТОРБЭК', 'ВОРФИНТ', 'МЕЛХОЛТ', 'ФОРВАР', 'ЛИНДРИГ', 'УТСУНД', 'СМОКОКА', 'МАЛАРЕН', 'ФЕЙКА', 'ВАЛЛКРАССИНГ', 'КОРНСНО', 'АЛЬВИНЕ', 'РОГКОРН', 'НЮФОНГАД', 'СМОЭТА', 'СТОРАБУ', 'ПРОДАКТ', 'ЭДЕЛВИК', 'СНИГЛАР', 'ФРЮКЕН', 'СКУТТРАН', 'ХОДДЕ', 'ШЭЛЛАНД', 'ФРАМКЭЛЛА', 'ТОППИГ', 'ДИПСИС', 'ТРУББТОГ', 'ДАГЛИГЕН', 'ВЕСКЕН', 'СМАКСЭТТА', 'СПРУТТИГ', 'ЭРТВИККЕР', 'ТАГГАД', 'ВАРЬЕРА', 'БАКСНА', 'ВЭНСКАПЛИГ', 'СПАРКА', 'ПАЛЬРА', 'СТИЛРЕН', 'МЕТОД', 'СОЛЛИНГЕ', 'КОЛЬДБИ', 'НАИН', 'ОМЛОПП', 'ФЛИСАТ', 'ЧИЛИПЕППЭР', 'ЭНЕРИДА', 'РЕСГОДС', 'БОРБЮ', 'ОНСКЛИГ', 'АРБОРИКОЛА', 'ЛОММАРП', 'СТАККХОЛЬМЕН', 'СВАЛЬНА', 'ФЕСТХОЛЬМЕН', 'ОМНЕЙД', 'ТАННИСБЮ', 'БУСУНГЕ', 'ДЕТОЛЬФ', 'ЛОНСЕТ', 'УППЛИСТ', 'ДВАЛА', 'ТОППДОН', 'БЬЕРНУМ', 'МОТТАГА', 'РУТЕР', 'БАЛУНГЕН', 'ХУСАРЭ', 'НОЙСЭМ', 'ТРЮГГ', 'ПРЕСТЕРА', 'КУТТЕРСМЮККЕ', 'САМСТЭММИГ', 'ЛЕДБЕРГ', 'ТОРХОЛЬМЕН', 'ЛИЛЛЬ', 'НИМОНЕ', 'РОТЕРА', 'ДРОПС', 'АСКВОЛЬ', 'ЭТЛА', 'ЛЕДАРЕ', 'ВИКЕДАЛЬ', 
         'РОМАНТИСК', 'НОРРФЛИ', 'ТРОЛЛЬБЕРГЕТ', 'БЛОМДОРФ', 'ТОЛЕРАНТ', 'МОТТЛИГ', 'ГЕНОМСНИТТ', 'МАРТОРП', 'ЭЛМАРЕН', 'АСПЕКТ', 'ИММЕЛЬН', 'ЭДСБРУК', 'ХИЛЬДРАН', 'ВИКАРЕ', 'МАТА', 'КУЛЛЭРНА', 'РАМСТА', 'ТУССОЙ', 'СТАКИГ', 'СМЮЛА', 'ГОРЭ', 'УЛЕБИ', 'СВАРТПЕППАР', 'ЙОНАКСЕЛЬ', 'РОДЕЛУНД', 'МИТТБИТ', 'АСКХОЛЬМЕН', 'ЛОТТАЛИ', 'КРИТТЕР', 'КУЛЛАБЕРГ', 'ДРАГБИ', 'РИСБЮН', 'ЭНДЛИГ', 'ЮППЕРЛИГ', 'ТРАТТВИВА', 'АБИДО', 'ХОГМОДИГ', 'БЛОВИНДА', 'КАЛЬКБРЭКЕН', 'ЭНГЛАЛИ', 'ГАТКАМОМИЛЛ', 'НИЛЬСОЛЛЕ', 'ФУЛЛАСТАД', 'КАЛАС', 'СУФФЛЕТТ', 'ГЛЕН', 'ФИСКБЕН', 'УППРЮМД', 'КАСКАДГРАН', 'ГРУССТАРР', 'ХЭЙР', 'КУНГСХОЛЬМЕН', 'ГРОСЕЙ', 'ФАНТАСТИСК', 'ЭДВАЛЛА', 'СМАСКА', 'ГЛИМРАНДЕ', 'СОККЕРБИТ', 'ОДЛА', 'ХИГИЕНИСК', 'КЛЕППСТАД', 'БУРГУЛЬТ', 'РУННЕН', 'КРИСТИНЕЛУНД', 'БЕТСО', 'СПАЙСИГ', 'ЭЛЬСЭБЭТ', 'КРИСТАЛЛЕР', 'ГЛАДОМ', 'РОТБЛОТА', 'РАССЛА', 'БЭВЕ', 
         'ЯККФРУКТ', 'САНДВЕДЕЛ', 'ЯКОБСБЮН', 'ОДЕНСВИК', 'ТОКРОЛИГ', 'БЕРНГАРД', 'ЛЕЙКНИ', 'БЬЙОРКБЕРГЕТ', 'ГЭНГА', 'ДОППА', 'САМВЕРКА', 'ФИЛЛЕН', 'БОЙСЕНБЭР', 'САМСО', 'КЛЮВЭ', 'ТРОНЭС', 'БАХТИАР', 'БЛИСКЭР', 'БЭКТИСТЕЛЬ', 'СВАМПИГ', 'ОЛИВМОЛЛА', 'ЛЕН', 'ЛЕНАСТ', 'КНАЛЛБОГЕ', 'ФОРЕНКЛА', 'ФОСКОН', 'ИНГАТОРП', 'БАРЭН', 'СЛАГСИДА', 'КНОД', 'КАСКЕР', 'ЛАППЛАНД', 'ПРАКТБРЭККА', 'КУГГИС', 'ХУГАД', 'ОРФЬЕЛЛЬ', 'СИББГУЛЬТ', 'ТИТТА', 'ТУЛЬСТА', 'ОЛМСТАД', 'РУНДЛИГ', 'РУМСМАЛЬВА', 'СМАРРА', 'ФИНСМАКАРЕ', 'ЛАССБЮН', 'СТИЛЕНЛИГ', 'ГРЭСМАРО', 'КРАГСТА', 'ХАУГА', 'ВАНГСТА', 'ИСТАД', 'НИССАФОРС', 'СПОРУП', 'ЭНТУЗИАЗМ', 'ЭНГСЛИЛЬЯ', 'ЛАККИСАР', 'РИСГОРДЕ', 'ЭРВФЬЕЛЛЕТ', 'ФОРТГО', 'УТДРАГ', 'ФУЛЛКОМЛИГ', 'ВЭРДЕРА', 'ЛИЛЛЬСВАН', 'БЛИКСТСНАББ', 'ЛУРПАССА', 'БЛАДВЕРК', 'ЭМТЕН', 'ХАМАРВИК', 'КУДДАРНА', 'КЛОКРЕН', 'ВИЛЬДЛИН', 'МЕТАЛЛИСК', 'БЛАСКА', 'ЛИКСИДИГ', 'ФРИДФУЛ', 'ВИННФАР', 'ФУЛЛСТЭНДИГ', 'МУНТЛИГ', 'ЭГЕНТЛИГ', 'АЛЬСТА', 'СИГНУМ', 'ЛАППВИКЕН', 'АЛЛЕРСЛЕВ', 'АННАМИА', 'ПАППИС', 'КВАРТС', 'ВОРДА', 'ТОНАД', 'ЭФТЕРСМАК', 'ТАУЛОВ', 'ВЭЛВОРДАД', 'СИББАРП', 'ЗАМИОКУЛКАС', 'ГАМЛАРЕД', 'СОЛБУ', 'ХИММЕЛЬСК', 'ЛУНДТРАВ', 'ОВЕРДЕРЛИГ', 'ХАТТЕФЬЕЛЛЬ', 'ТИЛЛЬРЕДА', 'БАРОМЕТР', 'ПИАЛОТТА', 'ГРЭЛЛЬСТА', 'УППСКАТТНИНГ', 'ФУЛЛЭНДАД', 'СУККУЛЕНТЫ', 
         'КУНГСХУЛЬТ', 'МАЛЛХОППА', 'ЭРИК', 'ИННЕРСКЭР', 'КИЛКЛЭМП', 'ЙЭЛТЕ', 'МАГАЗИН', 'ТОРНВИКЕН', 'ФИКУСОВИДНЫЙ', 'ГЛИММА', 'БОМУЛЬ', 'МОРГОНТИДИГ', 'УППНОРЭ', 'УНДЕРЛЭТТА', 'РИННИГ', 'МОЛЛАРП', 'ТИЛЛАГД', 'БРАМСОН', 'ФАСИНЕРА', 'АНТАГЕН', 'СНУДДА', 'БИЛЬД', 'ПЕРСГУЛЬТ', 'РЕНСАРЕ', 'КУНГСФОРС', 'СТЕКА', 'ВАЛЛОКСЕН', 'ЛЕИРСУНД', 'ЛЭМПЛИГ', 'ИНГМАРСЭ', 'ЛАКЭНЕ', 'ЛАУТЕРС', 'БАКТРАДИТИОН', 'ВИРРМО', 'КРИСМАСТ', 'ПЛУТТЕН', 'ФИНТСЕН', 'ГАМЛЕГУЛЬТ', 'ЙЭТТЕВАЛЛМО', 'СОРТЕРА', 'КАЛЬКГРУНД', 'БЕВАРА', 'ПРОФФСИГ', 'ДЭКАД', 'ТРОСС', 'ПЛИРА', 'ДОКСТА', 'СИНЛИГ', 'ФЭРГМОРА', 'ТРИЛЛИНГЕН', 'ЛУСТРУП', 'ФАДУ', 'ПЮСЛА', 'КРУКС', 'ГУРЛИ', 'РЭТТВИКЕН', 'СОММАРБИНКА', 'ДРОММАРЕ', 'СВАРТХО', 'ВАРДАГЕН', 'ГЕРТРУД', 'БУМАРКЕН', 'ОСВЕЙГ', 'ФРАМБРИНГА', 'ПОМП', 'ИЛЛЕСТА', 'ЦИТРУС', 'ЭРСЕТТА', 'АРВ', 'ХИСГУЛЬТ', 'ТВЭРС', 'ТРОЛЛЬБО', 'СТУРНЭС', 'ХЮВОН', 'ПЭРЛЬБАНД', 'ОДГЕР', 'ОДДЛАУГ', 'БЕСКАФФАД', 'ЛОХАЛЬС', 'ПУГГ', 'ЙЭРТА', 'ТЭРНО', 'СТОКГОЛЬМ', 
         'ЛЕТТАН', 'БЕХОВД', 'БРЕДЕВАД', 'УГГЛА', 'ЛИЛЛЬВИКЕН', 'МОППЕ', 'ПЛУТТИГ', 'ИНВЭНДИГ', 'РИСБЮГД', 'ФРЕБРУ', 'ФРИДЛЕВ', 'ЛАНГУР', 'БУСКБУ', 'ЮТХОЛЬМЕН', 'КАРТОТЕК', 'КРАНСКРАГЕ', 'ЛАТТО', 'ХИТ', 'НИПЛОККАД', 'МОНСАРП', 'ВОРКЭНСЛА', 'ЛУГГА', 'ТЬЕНА', 'МУЗИК', 'КАКТУСФИКОН', 'НОМИНЕЛЬ', 'АСКЕСТА', 'МЭЛАРО', 'БАРКАБУДА', 'СОФИА', 'СОЛВИДЕН', 'ВОНСБЭК', 'НИККЕБИ', 'ОРДНИНГ', 'ТРАТТ', 'ГУББРОРА', 'ДУНДРЭ', 'ЛИНДСХУЛЬТ', 'ТРАНГУЛЬТ', 'АРКЕЛЬСТОРП', 'АННСОФИ', 'СПИКЕН', 'НОРДМЕЛА', 'БЬЙОРКОН', 'ЛАТМАСК', 'КЮРРЕ', 'ВИСТОФТ', 'ОСТЕРИЛЬД', 'ФОРДУББЛА', 'ЮТТРАН', 'ЛЕВАНГ', 'ТЬЕРБЛОМСТЕР', 'ФРАСЕРА', 'БРОММО', 'АННАЛУИЗА', 'СИББЕН', 'РОММА', 'МАТТ', 'СУСИГ', 'РОСХУЛЬТ', 'КЕЛГРИС', 'МАРКУС', 'ХОЛ', 'ТИСКЕН', 'ТИЛЛЬГОНГ', 'ПАКС', 'ХАЛВМОНЕ', 'ТОММАРЮД', 'КАНАРСКИЙ', 'СУНДВИК', 'РОЛЛЕКА', 'ДОФТА', 'УНДЕРЛИГ', 'ВАЛЬБИЛДАД', 'ВИЛЬЕСТАРК', 'ГУНАТ', 'КОНУНГСЛИГ', 'РИГГА', 'ОЛОВ', 'МОРУМ', 'КУЛУН', 'ЛИВСОР', 'ТРЕБЕНТ', 'ЛЭТТНАД', 'СНАЙДАРЕ', 'ФРИТИДС', 'СИТА', 'АРБЕТЕ', 'ВИКЕРСУНД', 'ФЬЕДРАР', 'ХОЭТ', 'КЛИНГСТА', 'НОРРОКЕР', 'ТИДИГ', 'СКОЛЬД', 'КУББИС', 'ФЕЙЯН', 'АЛЕФЬЕЛЛЬ', 'СКАФТЕТ', 'ХОПКОК', 'КАПИТА', 'КВИСТ', 'ИНГАЛИЛЛ', 'ЛЭВА', 'СТРАПАТС', 'ХОРВИК', 'УТТЕР', 'КАЛКФЛАЙ', 'ЛЕНДА', 'КЛАКК', 'СУЛИГ', 'ПУРРИНГЛА', 'КНЭЛЛА', 'СМЕКА', 'СТЭРНБРЭККА', 'СИЛЛЬБУ', 'ГУЛЛЬКЛОКА', 'ОПТИМАЛЬ', 'ФИЛЬМИС', 'ГИММАРП', 'ГРЕЙА', 'ГУВЕТ', 'БАГГМУКК', 'БАККАБРУ', 'ЛОБЕРГЕТ', 'СМАКСИННЕ', 'ЛЕДЛЬЮС', 'РИББА', 'КНАРРА', 'ТИБАСТ', 'ИНГИМУНДА', 'СКУГГИС', 'СТОММА', 'ЯСНИНГ', 
         'АЛКАЛИСК', 'РУДСТА', 'КВИССЛЕ', 'ВЕНТИЛЕРА', 'ДИТТЭ', 'ХАННАЛЕНА', 'ГУЛЬКЛИНТ', 'УНДЕРСОКА', 'ХЕКТАР', 'БЕТИТАД', 'МИКС', 'ЛИЛЛАБУ', 'ВЭРДЕ', 'ВАРДО', 'КЛЮФТА', 'ЛУДДЕ', 'ИКЕА', 'УРКРАМАД', 'РАСТ', 'СКОТТОРП', 'БАГГАНЭС', 'СВАРТНОРА', 'ВИМСИГ', 'НОРБЕРГ', 'ПИЛКОН', 'БРИССУНД', 'ГОРТЕНЗИЯ', 'МАЙГУЛЛ', 'ЛОККИГ', 'САКСБОРГА', 'ФРЭКК', 'ХЭЛЬСА', 'ДУНДЕРГУББЕ', 'ФАБРИКОР', 'ЖЕЛТОВАТЫЙ', 'ГАББИГ', 'ХОВЛИГ', 'ЧУГ', 'СИ', 'ЛИЛЬТРЭСК', 'КЛУНКА', 'ТЬЕББА', 'ОМАР', 'ФАБЛЕР', 'ТУФФИНГ', 'ДАГНХИЛЬД', 'ФОКУСЕРА', 'РЭТТВИК', 'БРАНКИС', 'ФЛИСО', 'ВОРВИАЛ', 'СКУГХАЛЬ', 'ТУТЕМО', 'СМУССЛА', 'МАЛЬМ', 'ЛЭНСОС', 'ЛЭККЭ', 'СИЛЛИНГ', 'ФРИХЕТЭН', 'ТОФТБУ', 'ВЭГТОГ', 'ОБСЕРВАТОР', 'НЭВЛИНГЕ', 'ОДВАР', 'ОКСНЭ', 'ЧУГУ', 'СЕНСУЭЛЛ', 'ЛЭТТСКАЛАД', 'ДИТМАР', 'ФИНПУТСАД', 'ОРРЕВИК', 'ЭДЕЛЬХЕТ', 'ЛУРОЙ', 'ЛЭТТАД', 'ВИНТЕРКИНДЕЛЬ', 'ФАЛЬХОЛЬМЕН', 'УББЕТОРП', 'СЮВЕРТ', 'ОТЕРСКЕН', 'ТОФТАН', 'РЭККЛА', 'МОССЛЭНДА', 'СЕНАПСКОЛ', 'ВАТТУДАЛЕН', 'ГРЮББАН', 'ЛАНГЕСУНД', 'ФОЛЬЙЭНДЕ', 'ЛЕКМАН', 'ИСАНДЕ', 'АЙНА', 'ПЭРКЛА', 'ФЬЙАНТИГ', 'СЕДЛИГ', 'АДДЕ', 'СТОРЙОРМ', 'ОСАТИЛЬДА', 'ЛОКАБРУНН', 'МЮРХУЛЬТ', 'ФАНТАСТ', 'КРАМА', 'КНИППАРВ', 'ВИННЭСЕТ', 'ТРОДФРИ']

In [ ]:
names[:10]

['ХЕММАБАК',
 'РЕНБЛОММА',
 'ЗАКАРИАС',
 'ЛЕДФИР',
 'ТОРКАД',
 'ДИСКАД',
 'СОЛЬФРИД',
 'ВЕКЕТОГ',
 'ЛУНДСЛОК',
 'ГАРНЕРА']

In [ ]:
all_letters = set()
for name in names:
  all_letters.update(name)

all_letters = ['START', 'STOP'] + list(all_letters)

n_letters = len(all_letters) 
n_letters

32

In [ ]:
char_to_int = dict([(b,a) for a,b in enumerate(all_letters)])

In [ ]:
W = np.random.randn(4, 3)
W


array([[ 0.64031011,  0.66190474, -0.95061714],
       [ 0.90003419,  0.44739122, -1.18513628],
       [ 0.17365941, -0.61581967, -0.53302604],
       [ 1.414837  , -0.26893821,  0.73670571]])

In [ ]:
x = np.random.randn(3)
x

array([ 0.40060295, -1.05516379,  0.31241848])

In [ ]:
b = np.random.randn(4)
b

array([ 0.08038942, -1.14019433, -0.6682344 , -0.79355462])

In [ ]:
np.dot(W, x) + b

array([-0.65850874, -1.62196746, -0.1154025 ,  0.28716759])

In [ ]:
y = np.zeros(4)
for i in range(4):
  for j in range(3):
    y[i] += W[i, j] * x[j] 
  y[i] += b[i]

In [ ]:
y

array([-0.65850874, -1.62196746, -0.1154025 ,  0.28716759])